AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: selenium with headless chromium
Resources:
  Lambdium:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      FunctionName: lambdium
      Description: headless chromium running selenium
      # This needs to be fairly large: chromium needs a lot of memory
      MemorySize: 1156
      Timeout: 20
      Environment:
        Variables:
          CLEAR_TMP: "true"
      CodeUri: .
